version: '3.7'

services:
  web:
    container_name: seedy_users_web
    build:
      context: .
      dockerfile: Dockerfile 
#    command: python manage.py run -h 0.0.0.0
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py run -h 0.0.0.0; docker-compose exec web python manage.py'
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: seedy_users_db
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
#    ports:
#      - 5405:5432
#    restart: always

volumes:
  postgres_data: