# Imagen base de python 
FROM python:3.8

# Directorio de trabajo
WORKDIR /usr/src/app

# Indica al inteprete de Python que no genere archivos .pyc
ENV PYTHONDONTWRITEBYTECODE 1

# Indica a Python que su salida estandar se envie directamente 
# a la terminal, sin esperar en un buffer intermedio.
ENV PYTHONUNBUFFERED 1

# Indica a Flask en que modulo se encuetra la aplicacion
ENV FLASK_APP=manage

# Instalar netcat para script de espera de postgres
RUN apt-get update && apt-get install -y netcat

# Instalar dependencias
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -Ur requirements.txt

# Copiar archivos de proyecto al directorio de trabajo
COPY . /usr/src/app/
