# Docker-Composer para uso local
version: '3.7'

services:
  service_users_web:
    # Nombre del contenedor.
    container_name: container_users_web

    # Info de construcción del contenedor.
    build:
      # Directorio donde se encuentra el Dockerfile
      context: .
      # Nombre del Dockerfile
      dockerfile: Dockerfile.dev 
    
    entrypoint: ['/usr/src/app/entrypoint.sh']
    
    # TODO: Explicar esto
    volumes:
      - .:/usr/src/app/
    
    # Mapear puerto 5001 del contenedor al puerto 5000 de 
    # sistema operativo.
    ports:
      - 5001:5001
    
    # Variables de entorno para desarrollo y pruebas
    environment: 
      - FLASK_APP=manage
      - FLASK_ENV=development
      - APP_SETTINGS=backend_users.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@service_users_db:5432/users_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@service_users_db:5432/users_test

    # Este servicio 'service_users_web' depende de el servicio 
    # de base datos 'service_users_db'
    depends_on:
      - service_users_db

  service_users_db:
    # Nombre del contenedor 
    container_name: container_users_db

    # Construccion personalizada de postgres
    build: 
      # Directorio donde se encuentra el Dockerfile
      context: ./backend_users/db
      # Nombre del Dockerfile
      dockerfile: Dockerfile 
    
    # Exponemos puerto donde se ejecuta postgres
    expose:
      - 5432
    
    # Información de acceso a la base de datos local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
